# vim: set tabstop=2 expandtab softtabstop=2 shiftwidth=2 autoindent :

version: '2'
services:
  jnethack-server:
    build:
      context: jnethack-server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    labels:
      container_group: jnethack
    mem_limit: 64m
    restart: unless-stopped
    image: jnethack-server
    ports:
      - "${JNETHACK_EXTERNAL_PORT}:23"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dgldir:/home/nethack/dgldir:rw
      - nhdata:/home/nethack/nh366/var:rw
    networks:
      - jnethack-server

volumes:
  dgldir:
      driver: local
  nhdata:
      driver: local

networks:
  jnethack-server:
    driver: bridge
