# vim: set tabstop=2 expandtab softtabstop=2 shiftwidth=2 autoindent :

version: '2'
services:
  jnethack-server:
    build:
      context: jnethack-server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    labels:
      container_group: jnethack
    mem_limit: 64m
    restart: unless-stopped
    image: jnethack-server
    ports:
      - "${JNETHACK_EXTERNAL_PORT}:8080"
    environment:
      - TZ=${TZ}
      - NETHACKOPTIONS=${NETHACKOPTIONS}
      - GOTTY_CREDENTIAL=${GOTTY_CREDENTIAL}
      - GOTTY_TITLE_FORMAT=${GOTTY_TITLE_FORMAT}
      - GOTTY_PERMIT_WRITE=${GOTTY_PERMIT_WRITE}
    volumes:
      - nhdata:/nh366/var:rw
    networks:
      - jnethack-server

volumes:
  nhdata:
      driver: local

networks:
  jnethack-server:
    driver: bridge
